// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/sygus.proto

package sygus;

public final class Sygus {
  private Sygus() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface SygusProblemOrBuilder extends
      // @@protoc_insertion_point(interface_extends:sygus.SygusProblem)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string logic = 1;</code>
     * @return The logic.
     */
    java.lang.String getLogic();
    /**
     * <code>string logic = 1;</code>
     * @return The bytes for logic.
     */
    com.google.protobuf.ByteString
        getLogicBytes();

    /**
     * <code>string program = 2;</code>
     * @return The program.
     */
    java.lang.String getProgram();
    /**
     * <code>string program = 2;</code>
     * @return The bytes for program.
     */
    com.google.protobuf.ByteString
        getProgramBytes();
  }
  /**
   * Protobuf type {@code sygus.SygusProblem}
   */
  public static final class SygusProblem extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:sygus.SygusProblem)
      SygusProblemOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use SygusProblem.newBuilder() to construct.
    private SygusProblem(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SygusProblem() {
      logic_ = "";
      program_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new SygusProblem();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private SygusProblem(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              logic_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              program_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return sygus.Sygus.internal_static_sygus_SygusProblem_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return sygus.Sygus.internal_static_sygus_SygusProblem_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              sygus.Sygus.SygusProblem.class, sygus.Sygus.SygusProblem.Builder.class);
    }

    public static final int LOGIC_FIELD_NUMBER = 1;
    private volatile java.lang.Object logic_;
    /**
     * <code>string logic = 1;</code>
     * @return The logic.
     */
    @java.lang.Override
    public java.lang.String getLogic() {
      java.lang.Object ref = logic_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        logic_ = s;
        return s;
      }
    }
    /**
     * <code>string logic = 1;</code>
     * @return The bytes for logic.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getLogicBytes() {
      java.lang.Object ref = logic_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        logic_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PROGRAM_FIELD_NUMBER = 2;
    private volatile java.lang.Object program_;
    /**
     * <code>string program = 2;</code>
     * @return The program.
     */
    @java.lang.Override
    public java.lang.String getProgram() {
      java.lang.Object ref = program_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        program_ = s;
        return s;
      }
    }
    /**
     * <code>string program = 2;</code>
     * @return The bytes for program.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getProgramBytes() {
      java.lang.Object ref = program_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        program_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getLogicBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, logic_);
      }
      if (!getProgramBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, program_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getLogicBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, logic_);
      }
      if (!getProgramBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, program_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof sygus.Sygus.SygusProblem)) {
        return super.equals(obj);
      }
      sygus.Sygus.SygusProblem other = (sygus.Sygus.SygusProblem) obj;

      if (!getLogic()
          .equals(other.getLogic())) return false;
      if (!getProgram()
          .equals(other.getProgram())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + LOGIC_FIELD_NUMBER;
      hash = (53 * hash) + getLogic().hashCode();
      hash = (37 * hash) + PROGRAM_FIELD_NUMBER;
      hash = (53 * hash) + getProgram().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static sygus.Sygus.SygusProblem parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static sygus.Sygus.SygusProblem parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static sygus.Sygus.SygusProblem parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static sygus.Sygus.SygusProblem parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static sygus.Sygus.SygusProblem parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static sygus.Sygus.SygusProblem parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static sygus.Sygus.SygusProblem parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static sygus.Sygus.SygusProblem parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static sygus.Sygus.SygusProblem parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static sygus.Sygus.SygusProblem parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static sygus.Sygus.SygusProblem parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static sygus.Sygus.SygusProblem parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(sygus.Sygus.SygusProblem prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code sygus.SygusProblem}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:sygus.SygusProblem)
        sygus.Sygus.SygusProblemOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return sygus.Sygus.internal_static_sygus_SygusProblem_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return sygus.Sygus.internal_static_sygus_SygusProblem_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                sygus.Sygus.SygusProblem.class, sygus.Sygus.SygusProblem.Builder.class);
      }

      // Construct using sygus.Sygus.SygusProblem.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        logic_ = "";

        program_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return sygus.Sygus.internal_static_sygus_SygusProblem_descriptor;
      }

      @java.lang.Override
      public sygus.Sygus.SygusProblem getDefaultInstanceForType() {
        return sygus.Sygus.SygusProblem.getDefaultInstance();
      }

      @java.lang.Override
      public sygus.Sygus.SygusProblem build() {
        sygus.Sygus.SygusProblem result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public sygus.Sygus.SygusProblem buildPartial() {
        sygus.Sygus.SygusProblem result = new sygus.Sygus.SygusProblem(this);
        result.logic_ = logic_;
        result.program_ = program_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof sygus.Sygus.SygusProblem) {
          return mergeFrom((sygus.Sygus.SygusProblem)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(sygus.Sygus.SygusProblem other) {
        if (other == sygus.Sygus.SygusProblem.getDefaultInstance()) return this;
        if (!other.getLogic().isEmpty()) {
          logic_ = other.logic_;
          onChanged();
        }
        if (!other.getProgram().isEmpty()) {
          program_ = other.program_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        sygus.Sygus.SygusProblem parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (sygus.Sygus.SygusProblem) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object logic_ = "";
      /**
       * <code>string logic = 1;</code>
       * @return The logic.
       */
      public java.lang.String getLogic() {
        java.lang.Object ref = logic_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          logic_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string logic = 1;</code>
       * @return The bytes for logic.
       */
      public com.google.protobuf.ByteString
          getLogicBytes() {
        java.lang.Object ref = logic_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          logic_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string logic = 1;</code>
       * @param value The logic to set.
       * @return This builder for chaining.
       */
      public Builder setLogic(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        logic_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string logic = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearLogic() {
        
        logic_ = getDefaultInstance().getLogic();
        onChanged();
        return this;
      }
      /**
       * <code>string logic = 1;</code>
       * @param value The bytes for logic to set.
       * @return This builder for chaining.
       */
      public Builder setLogicBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        logic_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object program_ = "";
      /**
       * <code>string program = 2;</code>
       * @return The program.
       */
      public java.lang.String getProgram() {
        java.lang.Object ref = program_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          program_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string program = 2;</code>
       * @return The bytes for program.
       */
      public com.google.protobuf.ByteString
          getProgramBytes() {
        java.lang.Object ref = program_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          program_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string program = 2;</code>
       * @param value The program to set.
       * @return This builder for chaining.
       */
      public Builder setProgram(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        program_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string program = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearProgram() {
        
        program_ = getDefaultInstance().getProgram();
        onChanged();
        return this;
      }
      /**
       * <code>string program = 2;</code>
       * @param value The bytes for program to set.
       * @return This builder for chaining.
       */
      public Builder setProgramBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        program_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:sygus.SygusProblem)
    }

    // @@protoc_insertion_point(class_scope:sygus.SygusProblem)
    private static final sygus.Sygus.SygusProblem DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new sygus.Sygus.SygusProblem();
    }

    public static sygus.Sygus.SygusProblem getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<SygusProblem>
        PARSER = new com.google.protobuf.AbstractParser<SygusProblem>() {
      @java.lang.Override
      public SygusProblem parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SygusProblem(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<SygusProblem> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SygusProblem> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public sygus.Sygus.SygusProblem getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface SygusSolutionOrBuilder extends
      // @@protoc_insertion_point(interface_extends:sygus.SygusSolution)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>bool success = 1;</code>
     * @return The success.
     */
    boolean getSuccess();

    /**
     * <code>string answer = 2;</code>
     * @return The answer.
     */
    java.lang.String getAnswer();
    /**
     * <code>string answer = 2;</code>
     * @return The bytes for answer.
     */
    com.google.protobuf.ByteString
        getAnswerBytes();

    /**
     * <code>string errorMsg = 3;</code>
     * @return The errorMsg.
     */
    java.lang.String getErrorMsg();
    /**
     * <code>string errorMsg = 3;</code>
     * @return The bytes for errorMsg.
     */
    com.google.protobuf.ByteString
        getErrorMsgBytes();
  }
  /**
   * Protobuf type {@code sygus.SygusSolution}
   */
  public static final class SygusSolution extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:sygus.SygusSolution)
      SygusSolutionOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use SygusSolution.newBuilder() to construct.
    private SygusSolution(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SygusSolution() {
      answer_ = "";
      errorMsg_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new SygusSolution();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private SygusSolution(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              success_ = input.readBool();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              answer_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              errorMsg_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return sygus.Sygus.internal_static_sygus_SygusSolution_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return sygus.Sygus.internal_static_sygus_SygusSolution_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              sygus.Sygus.SygusSolution.class, sygus.Sygus.SygusSolution.Builder.class);
    }

    public static final int SUCCESS_FIELD_NUMBER = 1;
    private boolean success_;
    /**
     * <code>bool success = 1;</code>
     * @return The success.
     */
    @java.lang.Override
    public boolean getSuccess() {
      return success_;
    }

    public static final int ANSWER_FIELD_NUMBER = 2;
    private volatile java.lang.Object answer_;
    /**
     * <code>string answer = 2;</code>
     * @return The answer.
     */
    @java.lang.Override
    public java.lang.String getAnswer() {
      java.lang.Object ref = answer_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        answer_ = s;
        return s;
      }
    }
    /**
     * <code>string answer = 2;</code>
     * @return The bytes for answer.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getAnswerBytes() {
      java.lang.Object ref = answer_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        answer_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ERRORMSG_FIELD_NUMBER = 3;
    private volatile java.lang.Object errorMsg_;
    /**
     * <code>string errorMsg = 3;</code>
     * @return The errorMsg.
     */
    @java.lang.Override
    public java.lang.String getErrorMsg() {
      java.lang.Object ref = errorMsg_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        errorMsg_ = s;
        return s;
      }
    }
    /**
     * <code>string errorMsg = 3;</code>
     * @return The bytes for errorMsg.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getErrorMsgBytes() {
      java.lang.Object ref = errorMsg_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        errorMsg_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (success_ != false) {
        output.writeBool(1, success_);
      }
      if (!getAnswerBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, answer_);
      }
      if (!getErrorMsgBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, errorMsg_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (success_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(1, success_);
      }
      if (!getAnswerBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, answer_);
      }
      if (!getErrorMsgBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, errorMsg_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof sygus.Sygus.SygusSolution)) {
        return super.equals(obj);
      }
      sygus.Sygus.SygusSolution other = (sygus.Sygus.SygusSolution) obj;

      if (getSuccess()
          != other.getSuccess()) return false;
      if (!getAnswer()
          .equals(other.getAnswer())) return false;
      if (!getErrorMsg()
          .equals(other.getErrorMsg())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + SUCCESS_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getSuccess());
      hash = (37 * hash) + ANSWER_FIELD_NUMBER;
      hash = (53 * hash) + getAnswer().hashCode();
      hash = (37 * hash) + ERRORMSG_FIELD_NUMBER;
      hash = (53 * hash) + getErrorMsg().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static sygus.Sygus.SygusSolution parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static sygus.Sygus.SygusSolution parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static sygus.Sygus.SygusSolution parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static sygus.Sygus.SygusSolution parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static sygus.Sygus.SygusSolution parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static sygus.Sygus.SygusSolution parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static sygus.Sygus.SygusSolution parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static sygus.Sygus.SygusSolution parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static sygus.Sygus.SygusSolution parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static sygus.Sygus.SygusSolution parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static sygus.Sygus.SygusSolution parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static sygus.Sygus.SygusSolution parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(sygus.Sygus.SygusSolution prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code sygus.SygusSolution}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:sygus.SygusSolution)
        sygus.Sygus.SygusSolutionOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return sygus.Sygus.internal_static_sygus_SygusSolution_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return sygus.Sygus.internal_static_sygus_SygusSolution_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                sygus.Sygus.SygusSolution.class, sygus.Sygus.SygusSolution.Builder.class);
      }

      // Construct using sygus.Sygus.SygusSolution.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        success_ = false;

        answer_ = "";

        errorMsg_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return sygus.Sygus.internal_static_sygus_SygusSolution_descriptor;
      }

      @java.lang.Override
      public sygus.Sygus.SygusSolution getDefaultInstanceForType() {
        return sygus.Sygus.SygusSolution.getDefaultInstance();
      }

      @java.lang.Override
      public sygus.Sygus.SygusSolution build() {
        sygus.Sygus.SygusSolution result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public sygus.Sygus.SygusSolution buildPartial() {
        sygus.Sygus.SygusSolution result = new sygus.Sygus.SygusSolution(this);
        result.success_ = success_;
        result.answer_ = answer_;
        result.errorMsg_ = errorMsg_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof sygus.Sygus.SygusSolution) {
          return mergeFrom((sygus.Sygus.SygusSolution)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(sygus.Sygus.SygusSolution other) {
        if (other == sygus.Sygus.SygusSolution.getDefaultInstance()) return this;
        if (other.getSuccess() != false) {
          setSuccess(other.getSuccess());
        }
        if (!other.getAnswer().isEmpty()) {
          answer_ = other.answer_;
          onChanged();
        }
        if (!other.getErrorMsg().isEmpty()) {
          errorMsg_ = other.errorMsg_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        sygus.Sygus.SygusSolution parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (sygus.Sygus.SygusSolution) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private boolean success_ ;
      /**
       * <code>bool success = 1;</code>
       * @return The success.
       */
      @java.lang.Override
      public boolean getSuccess() {
        return success_;
      }
      /**
       * <code>bool success = 1;</code>
       * @param value The success to set.
       * @return This builder for chaining.
       */
      public Builder setSuccess(boolean value) {
        
        success_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool success = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearSuccess() {
        
        success_ = false;
        onChanged();
        return this;
      }

      private java.lang.Object answer_ = "";
      /**
       * <code>string answer = 2;</code>
       * @return The answer.
       */
      public java.lang.String getAnswer() {
        java.lang.Object ref = answer_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          answer_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string answer = 2;</code>
       * @return The bytes for answer.
       */
      public com.google.protobuf.ByteString
          getAnswerBytes() {
        java.lang.Object ref = answer_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          answer_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string answer = 2;</code>
       * @param value The answer to set.
       * @return This builder for chaining.
       */
      public Builder setAnswer(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        answer_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string answer = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearAnswer() {
        
        answer_ = getDefaultInstance().getAnswer();
        onChanged();
        return this;
      }
      /**
       * <code>string answer = 2;</code>
       * @param value The bytes for answer to set.
       * @return This builder for chaining.
       */
      public Builder setAnswerBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        answer_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object errorMsg_ = "";
      /**
       * <code>string errorMsg = 3;</code>
       * @return The errorMsg.
       */
      public java.lang.String getErrorMsg() {
        java.lang.Object ref = errorMsg_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          errorMsg_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string errorMsg = 3;</code>
       * @return The bytes for errorMsg.
       */
      public com.google.protobuf.ByteString
          getErrorMsgBytes() {
        java.lang.Object ref = errorMsg_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          errorMsg_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string errorMsg = 3;</code>
       * @param value The errorMsg to set.
       * @return This builder for chaining.
       */
      public Builder setErrorMsg(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        errorMsg_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string errorMsg = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearErrorMsg() {
        
        errorMsg_ = getDefaultInstance().getErrorMsg();
        onChanged();
        return this;
      }
      /**
       * <code>string errorMsg = 3;</code>
       * @param value The bytes for errorMsg to set.
       * @return This builder for chaining.
       */
      public Builder setErrorMsgBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        errorMsg_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:sygus.SygusSolution)
    }

    // @@protoc_insertion_point(class_scope:sygus.SygusSolution)
    private static final sygus.Sygus.SygusSolution DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new sygus.Sygus.SygusSolution();
    }

    public static sygus.Sygus.SygusSolution getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<SygusSolution>
        PARSER = new com.google.protobuf.AbstractParser<SygusSolution>() {
      @java.lang.Override
      public SygusSolution parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SygusSolution(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<SygusSolution> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SygusSolution> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public sygus.Sygus.SygusSolution getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_sygus_SygusProblem_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_sygus_SygusProblem_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_sygus_SygusSolution_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_sygus_SygusSolution_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021proto/sygus.proto\022\005sygus\".\n\014SygusProbl" +
      "em\022\r\n\005logic\030\001 \001(\t\022\017\n\007program\030\002 \001(\t\"B\n\rSy" +
      "gusSolution\022\017\n\007success\030\001 \001(\010\022\016\n\006answer\030\002" +
      " \001(\t\022\020\n\010errorMsg\030\003 \001(\tb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_sygus_SygusProblem_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_sygus_SygusProblem_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_sygus_SygusProblem_descriptor,
        new java.lang.String[] { "Logic", "Program", });
    internal_static_sygus_SygusSolution_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_sygus_SygusSolution_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_sygus_SygusSolution_descriptor,
        new java.lang.String[] { "Success", "Answer", "ErrorMsg", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
